apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-go-16-azur
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-go-16-azur 
  name: test-go-16-azur
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-go-16-azur 
